version: '3.4'

services:
  db:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "33061:3306"
  spotifyrooms:
    image: spotifyrooms
    volumes:
      - .:/code
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db
