# Generated by Django 3.2.13 on 2022-06-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_alter_room_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAccessToken',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.room')),
                ('token', models.CharField(max_length=180)),
                ('token_type', models.CharField(max_length=32)),
                ('scope', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expires_in', models.PositiveIntegerField()),
            ],
        ),
    ]
