# Generated by Django 3.2.13 on 2022-06-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifyaccesstoken_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccesstoken',
            name='refresh_token',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='spotifyaccesstoken',
            name='token',
            field=models.CharField(max_length=2048),
        ),
    ]
