# Generated by Django 3.2.13 on 2022-05-31 11:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(default=api.models.get_random_code, max_length=6, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=40, unique=True)),
                ('votes_to_skip', models.IntegerField()),
                ('user_can_pause', models.BooleanField(default=True)),
                ('user_can_control', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
