# Generated by Django 3.2.13 on 2022-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_votes',
            field=models.IntegerField(default=0),
        ),
    ]
