# Generated by Django 3.2.13 on 2022-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_can_control',
            field=models.BooleanField(default=True),
        ),
    ]
