# Generated by Django 3.2.13 on 2022-06-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
