# Generated by Django 3.2.13 on 2022-05-31 10:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_user_can_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.get_random_code, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
